### ISSUE TITLE
Integrating experimental changes

### ISSUE THREAD

**Issue by EgorPichkur** [conda-forge/pyvis-feedstock#9]
### Comment:

Hi,

our team is highly interested in integrating a custom package based on this [PR](https://github.com/WestHealth/pyvis/pull/91) into conda-forge. However, it looks like nobody is going to merge the changes into master and make a new release.
In the conda-forge gitter chat I was suggested to make a fork of the project and include it into conda-forge with a new name (pyvis-experimental, for example).

@ocefpaf , could you please share your opinion about the approach?

Thank you,
Egor

**Comment by ocefpaf** [comment]
> @ocefpaf , could you please share your opinion about the approach?

We always prefer to avoid forks b/c that can be confusing but if that is the only solution then a new package is fine.

**Comment by EgorPichkur** [comment]
Thank you for the answer!
